#pragma once

typedef enum _INTERNAL_MESSAGE_LEVEL
{
	msgInternal = 0,
	msgError,
	msgWarning,
	msgNormal,
	msgSequence,
	msgAll,
	msgNone,
}	INTERNAL_MESSAGE_LEVEL;

typedef enum _INTERNAL_MESSAGE_ENEMERATION
{
	msg_function_log = 0,
	msg_program_start,
	msg_program_end,
	msg_reset_detail_progress,
	msg_monitoring_start,
	msg_monitoring_stop,
	msg_motiongate_connecting,
	msg_motiongate_reconnecting,
	msg_motiongate_connected,
	msg_motiongate_disconnected,
	msg_motiongate_no_response,
	msg_motiongate_no_motor_response,
	msg_motiongate_busy,
	msg_motiongate_reboot,
	msg_motiongate_read_info,
	msg_motiongate_read_status,
	msg_motiongate_check_status,
	msg_motiongate_enter_admin,
	msg_motiongate_confirm_admin_on,
	msg_motiongate_exit_admin,
	msg_motiongate_confirm_admin_off,
	msg_motiongate_change_system_info,
	msg_motiongate_change_system_done,
	msg_motiongate_change_system_fail,
	msg_motiongate_alarm_reset,
	msg_scan_slave_start,
	msg_scan_slave_progress,
	msg_read_parameter,
	msg_write_parameter,
	msg_save_parameter,
	msg_compare_parameter,
	msg_read_position,
	msg_write_position,
	msg_save_position,
	msg_load_position,
	msg_compare_position,
	msg_compare_start,
	msg_compare_stop,
	msg_compare_fail,
	msg_compare_done,
	msg_backup_start,
	msg_backup_done,
	msg_backup_fail,
	msg_backup_stop,
	msg_change_motor_id,
	msg_restoration_start,
	msg_restoration_done,
	msg_restoration_fail,
	msg_restoration_stop,
	msg_factory_reset_start,
	msg_factory_reset_done,
	msg_factory_reset_fail,
	msg_factory_reset_stop,
	msg_initialize_start,
	msg_initialize_done,
	msg_initialize_fail,
	msg_initialize_stop,
	msg_homing_start,
	msg_homing_done,
	msg_homing_fail,
	msg_homing_stop,
	msg_homing_timer,
	msg_homing_all_start,
	msg_homing_all_done,
	msg_homing_all_fail,
	msg_homing_all_stop,
	msg_homing_all_timer,
	msg_homing_all_finish,
	msg_life_standard_detected_on,
	msg_life_standard_detected_off,
	msg_life_cycle_detected_on,
	msg_life_cycle_detected_off,
}	INTERNAL_MESSAGE_ENEMERATION;
